language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: nightly

    allow_failures:
        - php: nightly

    fast_finish: true

before_script:
    - composer self-update
    - composer global require --prefer-source phpunit/phpunit:"^6.5.0" php-coveralls/php-coveralls:^2.1.0
    - composer install --prefer-source
    - mkdir -p ./build/logs

script:
    - ~/.composer/vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_success:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ~/.composer/vendor/bin/php-coveralls -v; fi;'

notifications:
    email: false
